### ISSUE TITLE
Autocomplete for tags?

### ISSUE THREAD

**Issue by tesseract241** [drake7707/journal#3]
Just an idea for a potential feature:  
I find myself having to remember which spelling/capitalization I've used for my tags, and having to go back to fix it to avoid duplication (selfhosting vs self-hosting vs Self-hosting, as an example).
An autocomplete that looks up the already existing tags would solve this.

**Comment by drake7707** [comment]
I looked into that but the current tags input doesn't support it, it's either full select without free input or just free input, waiting for https://github.com/CreativeBulma/bulma-tagsinput/issues/13 to get implemented

**Comment by drake7707** [comment]
Though I found a "hacky" workaround by adding a datalist with id = null, which does add the browser based suggestion on the input element
```
<datalist id="null">
                        @foreach (var tag in Model.AvailableTags)
                        {
                            <option value="@tag" />
                        }
                        </datalist>
```
The docker image should be automatically updated
